name: CI (Java + React + Next)

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'web/**'
      - 'app/**'
      - '.github/workflows/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ===== Java Spring Boot (Maven) =====
  backend:
    name: backend (java)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Lint (Spotless/Checkstyle nếu có)
        run: |
          mvn -B -DskipTests=true spotless:check || true
          mvn -B -DskipTests=true checkstyle:check || true

      - name: Unit tests
        run: mvn -B -DskipITs=true test

      - name: Package (verify build)
        run: mvn -B -DskipITs=true -DskipTests package

  # ===== React (Node.js) =====
  web:
    name: web (react)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20.19.5
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present -- --ci --watchAll=false

      - name: Build
        run: npm run build --if-present

  # ===== Next.js (Node.js) =====
  app:
    name: app (nextjs)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20.19.5
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.5'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present -- --ci --watchAll=false

      - name: Build
        run: npm run build --if-present
